In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
d=pd.read_csv("/content/drive/MyDrive/internship/Market_Basket_Optimisation.csv",header=None)

In [ ]:
d.isnull().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [ ]:
d.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
transactions=[]
for i in range(0,len(d)):
  transactions.append([str(d.values[i,j])for j in range (0,20)
    if str(d.values[i,j])!='NaN'])

In [ ]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.12/dist-packages (1.1.2)

In [ ]:
from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.4,min_left=3,min_length=2,max_length=2)
results=list(rules)
results

[RelationRecord(items=frozenset({'nan'}), support=0.9998666844420744, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.9998666844420744, lift=1.0)]),
 RelationRecord(items=frozenset({'almonds', 'nan'}), support=0.020263964804692707, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'nan'}), confidence=0.9934640522875817, lift=0.9935965141612201)]),
 RelationRecord(items=frozenset({'nan', 'antioxydant juice'}), support=0.008798826823090255, ordered_statistics=[OrderedStatistic(items_base=frozenset({'antioxydant juice'}), items_add=frozenset({'nan'}), confidence=0.9850746268656716, lift=0.9852059701492537)]),
 RelationRecord(items=frozenset({'asparagus', 'nan'}), support=0.004666044527396347, ordered_statistics=[OrderedStatistic(items_base=frozenset({'asparagus'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'avocado', 'nan'}), support=0.03319557392347687, ordered_statistics=[OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'nan'}), confidence=0.996, lift=0.9961328)]),
 RelationRecord(items=frozenset({'babies food', 'nan'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'babies food'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'bacon', 'nan'}), support=0.008665511265164644, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bacon'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'barbecue sauce', 'nan'}), support=0.010798560191974404, ordered_statistics=[OrderedStatistic(items_base=frozenset({'barbecue sauce'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'black tea', 'nan'}), support=0.014264764698040262, ordered_statistics=[OrderedStatistic(items_base=frozenset({'black tea'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'blueberries', 'nan'}), support=0.009198773496867084, ordered_statistics=[OrderedStatistic(items_base=frozenset({'blueberries'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'body spray'}), support=0.011465137981602452, ordered_statistics=[OrderedStatistic(items_base=frozenset({'body spray'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'brownies'}), support=0.03372883615517931, ordered_statistics=[OrderedStatistic(items_base=frozenset({'brownies'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'bug spray', 'nan'}), support=0.008665511265164644, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bug spray'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'burger sauce', 'nan'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'burger sauce'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'burgers', 'nan'}), support=0.0871883748833489, ordered_statistics=[OrderedStatistic(items_base=frozenset({'burgers'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'butter', 'nan'}), support=0.030129316091187842, ordered_statistics=[OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'cake', 'nan'}), support=0.08105585921877083, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cake'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'candy bars', 'nan'}), support=0.009732035728569524, ordered_statistics=[OrderedStatistic(items_base=frozenset({'candy bars'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'carrots', 'nan'}), support=0.01533128916144514, ordered_statistics=[OrderedStatistic(items_base=frozenset({'carrots'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'cauliflower', 'nan'}), support=0.004799360085321957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cauliflower'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'cereals', 'nan'}), support=0.025729902679642713, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cereals'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'champagne', 'nan'}), support=0.04679376083188908, ordered_statistics=[OrderedStatistic(items_base=frozenset({'champagne'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'chicken'}), support=0.05999200106652446, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'chili', 'nan'}), support=0.0061325156645780565, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chili'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'chocolate', 'nan'}), support=0.1638448206905746, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'chocolate bread', 'nan'}), support=0.004266097853619517, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate bread'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'chutney', 'nan'}), support=0.0041327822956939075, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chutney'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'cider', 'eggs'}), support=0.004266097853619517, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'eggs'}), confidence=0.4050632911392405, lift=2.2539909101153137)]),
 RelationRecord(items=frozenset({'cider', 'nan'}), support=0.010531929076123183, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'clothes accessories', 'nan'}), support=0.008398880149313425, ordered_statistics=[OrderedStatistic(items_base=frozenset({'clothes accessories'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'cookies', 'nan'}), support=0.08038928142914278, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cookies'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'cooking oil', 'nan'}), support=0.0510598586855086, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cooking oil'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'corn', 'nan'}), support=0.004799360085321957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'corn'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'cottage cheese'}), support=0.03172910278629516, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cottage cheese'}), items_add=frozenset({'nan'}), confidence=0.9958158995815899, lift=0.9959486750348674)]),
 RelationRecord(items=frozenset({'dessert wine', 'nan'}), support=0.004399413411545127, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dessert wine'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'eggplant', 'nan'}), support=0.013198240234635382, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggplant'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'eggs'}), support=0.17970937208372217, ordered_statistics=[OrderedStatistic(items_base=frozenset({'eggs'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'energy bar', 'nan'}), support=0.027063058258898813, ordered_statistics=[OrderedStatistic(items_base=frozenset({'energy bar'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'energy drink', 'nan'}), support=0.026529796027196375, ordered_statistics=[OrderedStatistic(items_base=frozenset({'energy drink'}), items_add=frozenset({'nan'}), confidence=0.995, lift=0.9951326666666667)]),
 RelationRecord(items=frozenset({'nan', 'escalope'}), support=0.0793227569657379, ordered_statistics=[OrderedStatistic(items_base=frozenset({'escalope'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'extra dark chocolate', 'mineral water'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'mineral water'}), confidence=0.47777777777777775, lift=2.0043686303753416)]),
 RelationRecord(items=frozenset({'extra dark chocolate', 'nan'}), support=0.011998400213304892, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'flax seed'}), support=0.009065457938941474, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flax seed'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'french fries', 'nan'}), support=0.1709105452606319, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french fries'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'french wine', 'nan'}), support=0.022530329289428077, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french wine'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'fresh bread', 'nan'}), support=0.043060925209972005, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh bread'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'fresh tuna', 'nan'}), support=0.022263698173576856, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'fromage blanc', 'nan'}), support=0.013598186908412212, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'frozen smoothie', 'nan'}), support=0.0631915744567391, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen smoothie'}), items_add=frozenset({'nan'}), confidence=0.9978947368421054, lift=0.9980277894736843)]),
 RelationRecord(items=frozenset({'nan', 'frozen vegetables'}), support=0.09532062391681109, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'gluten free bar', 'nan'}), support=0.006932409012131715, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gluten free bar'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'grated cheese', 'nan'}), support=0.0523930142647647, ordered_statistics=[OrderedStatistic(items_base=frozenset({'grated cheese'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'green beans'}), support=0.008665511265164644, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green beans'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'green grapes', 'nan'}), support=0.008932142381015865, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green grapes'}), items_add=frozenset({'nan'}), confidence=0.985294117647059, lift=0.9854254901960786)]),
 RelationRecord(items=frozenset({'green tea', 'nan'}), support=0.13198240234635383, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green tea'}), items_add=frozenset({'nan'}), confidence=0.9989909182643796, lift=0.9991241170534815)]),
 RelationRecord(items=frozenset({'ground beef', 'mineral water'}), support=0.040927876283162246, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'mineral water'}), confidence=0.41655359565807326, lift=1.7475215442008991)]),
 RelationRecord(items=frozenset({'ground beef', 'nan'}), support=0.09825356619117451, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'gums', 'nan'}), support=0.013464871350486601, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gums'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'ham', 'nan'}), support=0.026529796027196375, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ham'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'hand protein bar', 'nan'}), support=0.005199306759098787, ordered_statistics=[OrderedStatistic(items_base=frozenset({'hand protein bar'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'herb & pepper', 'nan'}), support=0.04946007199040128, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'honey', 'nan'}), support=0.047327023063591524, ordered_statistics=[OrderedStatistic(items_base=frozenset({'honey'}), items_add=frozenset({'nan'}), confidence=0.997191011235955, lift=0.9973239700374531)]),
 RelationRecord(items=frozenset({'hot dogs', 'nan'}), support=0.03239568057592321, ordered_statistics=[OrderedStatistic(items_base=frozenset({'hot dogs'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'ketchup', 'nan'}), support=0.004399413411545127, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ketchup'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'mineral water', 'light cream'}), support=0.007332355685908546, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'mineral water'}), confidence=0.4700854700854701, lift=1.9720979368630376)]),
 RelationRecord(items=frozenset({'nan', 'light cream'}), support=0.01559792027729636, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'light mayo', 'nan'}), support=0.027196373816824423, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light mayo'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'low fat yogurt', 'nan'}), support=0.07638981469137449, ordered_statistics=[OrderedStatistic(items_base=frozenset({'low fat yogurt'}), items_add=frozenset({'nan'}), confidence=0.9982578397212545, lift=0.9983909407665507)]),
 RelationRecord(items=frozenset({'nan', 'magazines'}), support=0.010931875749900012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'magazines'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'mashed potato', 'nan'}), support=0.0041327822956939075, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mashed potato'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'mayonnaise', 'nan'}), support=0.0061325156645780565, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mayonnaise'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'meatballs'}), support=0.020930542594320756, ordered_statistics=[OrderedStatistic(items_base=frozenset({'meatballs'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'melons', 'nan'}), support=0.011998400213304892, ordered_statistics=[OrderedStatistic(items_base=frozenset({'melons'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'nan', 'milk'}), support=0.12958272230369283, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0001333333333333)]),
 RelationRecord(items=frozenset({'mineral water', 'nan'}), support=0.23823490201306494, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mineral water'}), items_add=frozenset({'nan'}), confidence=0.999440715883669, lift=0.9995739746457868)]),
 RelationRecord(items=frozenset({'mineral water', 'nonfat milk'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'nonfat milk'}), items_add=frozenset({'mineral water'}), confidence=0.4871794871794871, lift=2.0438105891126024)]),
 RelationRecord(items=frozenset({'mineral water', 'olive oil'}), support=0.027596320490601255, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'mineral water'}), confidence=0.4190283400809717, lift=1.7579035676439423)]),
 RelationRecord(items=frozenset({'mineral water', 'protein bar'}), support=0.007732302359685375, ordered_statistics=[OrderedStatistic(items_base=frozenset({'protein bar'}), items_add=frozenset({'mineral water'}), confidence=0.41726618705035967, lift=1.7505110005954967)]),
 RelationRecord(items=frozenset({'mineral water', 'rice'}), support=0.007732302359685375, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rice'}), items_add=frozenset({'mineral water'}), confidence=0.41134751773049644, lift=1.7256810573246386)]),
 RelationRecord(items=frozenset({'mineral water', 'salmon'}), support=0.017064391414478068, ordered_statistics=[OrderedStatistic(items_base=frozenset({'salmon'}), items_add=frozenset({'mineral water'}), confidence=0.4012539184952978, lift=1.6833364891684726)]),
 RelationRecord(items=frozenset({'soup', 'mineral water'}), support=0.023063591521130515, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'mineral water'}), confidence=0.45646437994722955, lift=1.9149548735929356)]),
 RelationRecord(items=frozenset({'mineral water', 'strong cheese'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'strong cheese'}), items_add=frozenset({'mineral water'}), confidence=0.4137931034482759, lift=1.7359407544549876)]),
 RelationRecord(items=frozenset({'mineral water', 'tomato sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'mineral water'}), confidence=0.40566037735849053, lift=1.7018224220167995)]),

In [ ]:
#results[1]
#results[2][0][0]

In [ ]:
def inspect(results):
    lhs         = [tuple(rule[2][0][0])[0] for rule in results if 'nan' not in rule[0]]
    rhs         = [tuple(rule[2][0][1])[0] for rule in results if 'nan' not in rule[0]]
    supports    = [rule[1] for rule in results if 'nan' not in rule[0]]
    confidences = [rule[2][0][2] for rule in results if 'nan' not in rule[0]]
    lifts       = [rule[2][0][3] for rule in results if 'nan' not in rule[0]]
    return list(zip(lhs, rhs, supports, confidences, lifts))
results_df = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])
display(results_df)

          Left Hand Side Right Hand Side   Support  Confidence      Lift
0                  cider            eggs  0.004266    0.405063  2.253991
1   extra dark chocolate   mineral water  0.005733    0.477778  2.004369
2            ground beef   mineral water  0.040928    0.416554  1.747522
3            light cream   mineral water  0.007332    0.470085  1.972098
4            nonfat milk   mineral water  0.005066    0.487179  2.043811
5              olive oil   mineral water  0.027596    0.419028  1.757904
6            protein bar   mineral water  0.007732    0.417266  1.750511
7                   rice   mineral water  0.007732    0.411348  1.725681
8                 salmon   mineral water  0.017064    0.401254  1.683336
9                   soup   mineral water  0.023064    0.456464  1.914955
10         strong cheese   mineral water  0.003200    0.413793  1.735941
11          tomato sauce   mineral water  0.005733    0.405660  1.701822
12         strong cheese       spaghetti  0.003733    0.482759  2.772720
13          tomato sauce       spaghetti  0.006266    0.443396  2.546642