In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
d=pd.read_csv("/content/drive/MyDrive/internship/Market_Basket_Optimisation.csv",header=None)

In [ ]:
d.isnull().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [ ]:
d.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pip install pyEclat pandas

Requirement already satisfied: pyEclat in /usr/local/lib/python3.12/dist-packages (1.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in /usr/local/lib/python3.12/dist-packages (from pyEclat) (2.0.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from pyEclat) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
from pyECLAT import ECLAT

In [ ]:
transactions = []
for i in range(len(d)):
    transactions.append(
        [str(d.values[i, j])
         for j in range(len(d.columns))
         if str(d.values[i, j]) != 'nan']
    )

In [ ]:
df = pd.DataFrame(transactions)

In [ ]:
eclat = ECLAT(data=df)

In [ ]:
indices, support = eclat.fit(min_support=0.03,
                             min_combination=1,
                             max_combination=3)

Combination 1 by 1

36it [00:01, 28.14it/s]

Combination 2 by 2

630it [00:13, 46.10it/s]

Combination 3 by 3

7140it [02:31, 47.07it/s]

In [ ]:
result = pd.DataFrame({
    'Itemset': support.keys(),
    'Support': support.values()
})

In [ ]:
result = result.sort_values(by='Support', ascending=False)

In [ ]:
print(result.head(20))

              Itemset   Support
20      mineral water  0.238368
19               eggs  0.179709
27          spaghetti  0.174110
12       french fries  0.170911
21          chocolate  0.163845
16          green tea  0.132116
11               milk  0.129583
2         ground beef  0.098254
10  frozen vegetables  0.095321
5            pancakes  0.095054
32            burgers  0.087188
3                cake  0.081056
23            cookies  0.080389
0            escalope  0.079323
24     low fat yogurt  0.076523
17             shrimp  0.071457
8            tomatoes  0.068391
13          olive oil  0.065858
6     frozen smoothie  0.063325
26             turkey  0.062525